name: e2e test reminder comment
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment-in-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning: Reminder to manually run end to end tests in https://github.com/eastgenomics/s3_upload/tree/main/tests/e2e\n\nThese may be run with the following: `python3 -m pytest tests/e2e/'
            })